### ISSUE TITLE
packet injection not working?

### ISSUE THREAD

**Issue by merrychrishna** [Shubhamvis98/kali-pinephone#1]
i think packet injection is not working. i put the card in montior mode but when i deauth i dont get a handshake back so i think the deauth is doing nothing.

and i dont know if this is related but when i run "sudo airmon-ng start wlan0" my chipset is not detected as seen below.

PHY     Interface       Driver          Chipset

phy0    wlan0           rtl8723cs       unable to detect for sdio 0x024c:0xb703

**Comment by Shubhamvis98** [comment]
Currently only deauth working.
As I mentioned in the release that I reverted back to mobian's kernel.
Last day I successfully built the kernel.
So, we'll add packet injection soon.

**Comment by merrychrishna** [comment]
sweet thats great news. thanks. do you have an idea of how soon that will be added?

**Comment by Shubhamvis98** [comment]
currently, I'm only doing all the things, like packaging and building the kernel. And I haven't enough time to try new things.
so no idea when we got packet injection mode.

**Comment by Shubhamvis98** [comment]
![IMG_20220317_212027](https://user-images.githubusercontent.com/43336210/159803478-76ef9daf-9d47-4574-81ef-da50e07ea541.jpg)

I tried and got this. When I try packet injection in monitor mode then it fails but when i try it in managed mode then it shows that "Injection is working!".

**Comment by merrychrishna** [comment]
thanks so much that works for me

**Comment by Shubhamvis98** [comment]
> thanks so much that works for me

I also informed @kimocoder about this issue.
Maybe he'll fine a way to achieve packet injection in monitor mode also.

**Comment by merrychrishna** [comment]
oh thats awesome

**Comment by safarifox** [comment]
try wifite..

**Comment by Shubhamvis98** [comment]
You can try using iwconfig to get into monitor mode, if you use iwconfig then packet injection will work.

<div style="display:inline-flex">
<img width="400px" src="https://user-images.githubusercontent.com/43336210/180941285-8ced5280-9807-49cd-98a6-c9593d5ed045.jpg">
<img width="400px" src="https://user-images.githubusercontent.com/43336210/180941301-7a9ed2f8-11ab-4db4-852c-674f05dd3db3.jpg">
</div>

**Comment by Shubhamvis98** [comment]
The rtl8723cs driver has some issues, as when I tried using `iwconfig wlan0 mode monitor` then only iwconfig shows status **monitor** but not in `iw wlan0 info` also **packet injection works**.
But when I tried using `airmon-ng start wlan0`, both status changed to **monitor** but packet injection not working

**Comment by merrychrishna** [comment]
Ah. Ok. Good testing

**Comment by covar2077** [comment]
Hi i cannot setup monitor mode on wlan0 neither with iwconfig nor airmon-ng. I have pinephone pro with posh with nethunter. Any help?

**Comment by Shubhamvis98** [comment]
> Hi i cannot setup monitor mode on wlan0 neither with iwconfig nor airmon-ng. I have pinephone pro with posh with nethunter. Any help?

Both phones have different wifi chipsets. Currently, only pinephone(non-pro) supports packet injection. and I don't have a pro so I can't help with this. But you can try patching the driver maybe this helps.

**Comment by covar2077** [comment]
> > Hi i cannot setup monitor mode on wlan0 neither with iwconfig nor airmon-ng. I have pinephone pro with posh with nethunter. Any help?
> 
> Both phones have different wifi chipsets. Currently, only pinephone(non-pro) supports packet injection. and I don't have a pro so I can't help with this. But you can try patching the driver maybe this helps.

Hi,
I' m trying to patch the drivers by downloading the source kernel and compile them. The last compile attempt was successful but the phone could not restart. Could you share some hints on how to patch the drivers?
