### ISSUE TITLE
nethunter root password

### ISSUE THREAD

**Issue by jbyanjankar** [Shubhamvis98/kali-pinephone#15]
getting an error message "kali is not in the sudoers file" in the latest build while running nethunter app

https://github.com/Shubhamvis98/kali-pinephone/releases/tag/20230926

**Comment by Shubhamvis98** [comment]
Apologies, forget to add the user to sudo and other groups. There's no root password in it, you can set it with sudo after doing below workaround.
You can fix sudo by mounting your device in you pc with tow-boot mass storage and run bellow command
`sed -i '/^sudo/s/$/kali/' {/etc/group of pinephone rootfs}`
or just edit the `/etc/group` file and add `kali` at the end of <pre>sudo:x:27:</pre>
it should be like this <pre>sudo:x:27:kali</pre> now you can start you pinephone the sudo permission will be fixed and then you have to run bellow command to fix sound and other permissions
`sudo usermod -aG dialout,audio,video,plugdev,input,render,bluetooth,feedbackd kali`

**Comment by Shubhamvis98** [comment]
I'm rebuilding the image, it'll be available in an hour.
you can try that as well, i removed the previous build as of now.

**Comment by jbyanjankar** [comment]
> I'm rebuilding the image, it'll be available in an hour. you can try that as well, i removed the previous build as of now.

Perfect 💯 I will test it once its available here

**Comment by Shubhamvis98** [comment]
@jbyanjankar new build uploaded, with audio fix for pinephonepro.

**Comment by jbyanjankar** [comment]
> @jbyanjankar new build uploaded, with audio fix for pinephonepro.

Perfect. I will download and test it out.

**Comment by Shubhamvis98** [comment]
Closing as this issue has been fixed. Open it if you face any other issue.
Thanks
