### ISSUE TITLE
Add image build instructions

### ISSUE THREAD

**Issue by orhun** [Shubhamvis98/kali-pinephone#2]
Hey, thanks for this! I've been using kali on Pinephone for the past 2 weeks and it's running great.

I was wondering if it is possible to get the instructions for preparing a custom Kali Linux image. Maybe update `README.md` with the build instructions? Or even better, provide a script? I'm really curious about how you build these images.

**Comment by Shubhamvis98** [comment]
It's only debootstrap-ed, nothing else.
I manually install all packages after creating the rootfs.
Like phosh network-manager etc.
