### ISSUE TITLE
Not booting...

### ISSUE THREAD

**Issue by Negalolz** [Shubhamvis98/kali-pinephone#23]
Kali-Pinephone-Pro 
on last version of Phosh not booting at all, on sd card and on main MMC....

Dunno what to do. =/

**Comment by Shubhamvis98** [comment]
Hi @Negalolz,
Is this the installer image that you're trying to boot?

**Comment by Shubhamvis98** [comment]
Could you please try the below solution and let me know if it's working or not:
1. Boot PPP in mass storage mode (Vol+ power on)
2. Mount first(boot) partition
3. Rename "initrd.img-6.1-rockchip" with "initrd.img-6.1-rockchip.zst"
`mv initrd.img-6.1-rockchip initrd.img-6.1-rockchip.zst`
4. `zstdcat initrd.img-6.1-rockchip.zst | gzip -c > initrd.img-6.1-rockchip`
5. `rm initrd.img-6.1-rockchip.zst`

**Comment by Negalolz** [comment]
sorry , installing for 2 hours packages on previous version of Phosh.. 27.09
maybe later.

Got another question, will it be repo for updating kernel ? Or could i build custom one for Pinephone pro, cause wifi injections not working at kernel Rockchip

**Comment by Shubhamvis98** [comment]
the mobian repo is already enabled so you'll get kernel updates through apt.
but packet injection isn't working in pinephone pro as of now. and i don't have a pro so can't do anything with that.
you can try to patch the kernel, maybe you can find the solution to enable packet injection.

**Comment by Negalolz** [comment]
key okay , thanks

**Comment by Negalolz** [comment]
sorry for late question.

But where i Could get stock code of Pinephone kernel ?

**Comment by Shubhamvis98** [comment]
> sorry for late question.
> 
> But where i Could get stock code of Pinephone kernel ?

You can clone from here https://salsa.debian.org/Mobian-team/devices/kernels

**Comment by Negalolz** [comment]
wow , momental answer. thanks alot !

**Comment by Negalolz** [comment]
> 4\. zstdcat initrd.img-6.1-rockchip.zst | gzip -c > initrd.img-6.1-rockchip

not worked... boot loop

**Comment by Negalolz** [comment]
solved initramfs from previous version worked !

**Comment by Shubhamvis98** [comment]
Is the installer worked correctly. I mean with FDE?

**Comment by Negalolz** [comment]
sorry was to fast to answer, no it isn't

**Comment by Negalolz** [comment]
should i put old kernel , from previous version into root boot dir. or installer dir , cause i have nothing in that directories.

**Comment by Shubhamvis98** [comment]
Give it a try, but even if it boots, the installation will break at update (I guess). I got the error from a user and the log shows "initramfs unpack failed", this issue occurs only when I make initramfs with cryptsetup. As of now, i suggest you to not try the setup image. I'll build another one and let you know.

**Comment by Negalolz** [comment]
okay, and another question, does waydroid run okay on kali image ?

**Comment by Shubhamvis98** [comment]
I never tried waydroid. if it works on mobian or any other distro, it'll work in kali as well.

**Comment by Negalolz** [comment]
yoyoyo
