### ISSUE TITLE
Camera isn’t working 

### ISSUE THREAD

**Issue by Sh31ks0n** [Shubhamvis98/kali-pinephone#24]
Hey my camera isn’t working with the latest version I’m using pine phone pro

anyone got drivers? I need some help 😅

**Comment by Shubhamvis98** [comment]
What error Megapixels showing?

**Comment by Sh31ks0n** [comment]
when im trying to launch megapixels look like its crash

**Comment by Shubhamvis98** [comment]
I think the Megapixels package doesn't contain pinephonepro configuration file. That's why its not working.

**Comment by Shubhamvis98** [comment]
Was it working previously or in any other OS?
You can get the pinephonepro configuration from this repo https://github.com/kgmt0/megapixels/tree/master/config

**Comment by covar2077** [comment]
I managed to make the camera work. I have installed megapixels from here https://github.com/kgmt0/megapixels 
Just follow the instructions.
