### ISSUE TITLE
instal via jump drive gives low space

### ISSUE THREAD

**Issue by safarifox** [Shubhamvis98/kali-pinephone#4]
Hi and thanks for developing such product
It will be great if you can help with low space issue 
method i use 
1) install jump drive on sd card and run  
2)connected jump drive pinephone and flushed it

for some reason im always getting that /dev/mmcblkp2p is always 2.7 gig
and its always 99% full

**Comment by safarifox** [comment]
solution 
can connect pine phone in  jump drive mode to Linux commuter and resize

**Comment by Shubhamvis98** [comment]
> solution can connect pine phone in jump drive mode to Linux commuter and resize

already mentioned in install instructions and in pinephone software release
