### ISSUE TITLE
No USB devices found

### ISSUE THREAD

**Issue by d4rkw1n9** [Shubhamvis98/kali-pinephone#43]
Hi there. Just managed to install this dual boot Kali on my Poco F1, and am very happy so far. Unfortunately, I don't see any usb devices when connected. Dmesg is not showing anything usb related either. Do I need to install anything else on top of the base install? Just installed the image on sdcard and then (flashed and) booted the specific .img file.

Thanks in advance - nice project! Hopefully monitor mode and injection will come on wlan0 :))

**Comment by Shubhamvis98** [comment]
> Hi there. Just managed to install this dual boot Kali on my Poco F1, and am very happy so far. Unfortunately, I don't see any usb devices when connected. Dmesg is not showing anything usb related either. Do I need to install anything else on top of the base install? Just installed the image on sdcard and then (flashed and) booted the specific .img file.
> 
> Thanks in advance - nice project! Hopefully monitor mode and injection will come on wlan0 :))

Hi @d4rkw1n9,
Thanks for the feedback.
OTG won't work in pocof1 without external power source.
You can watch this tutorial to make otg work: https://youtu.be/bjhgKxhgmIY

**Comment by d4rkw1n9** [comment]
> > Hi there. Just managed to install this dual boot Kali on my Poco F1, and am very happy so far. Unfortunately, I don't see any usb devices when connected. Dmesg is not showing anything usb related either. Do I need to install anything else on top of the base install? Just installed the image on sdcard and then (flashed and) booted the specific .img file.
> > 
> > Thanks in advance - nice project! Hopefully monitor mode and injection will come on wlan0 :))
> 
> Hi @d4rkw1n9,
> Thanks for the feedback.
> OTG won't work in pocof1 without external power source and Also need to make a change in dtb.
> You can watch this tutorial to make otg work: https://youtu.be/bjhgKxhgmIY

Thanks a lot for the quick reply! Might need to change to OnePlus 6 or 6T then, as I am aiming to use the dual boot device as daily driver (without carrying external battery pack with me just to be all time ready for pentesting). I hope the OnePlus are fine with this regard. 

Keep up the good work!

**Comment by Shubhamvis98** [comment]
Nah, thos issue is only with pocof1.
