### ISSUE TITLE
[POCO F1] Adapters seen with lsusb, but not with iwconfig

### ISSUE THREAD

**Issue by d4rkw1n9** [Shubhamvis98/kali-pinephone#44]
Hey again. 

Just followed the other video to get adapters working on the Poco F1. So far it worked, although the adapters are not recognized as such when running iwconfig for example. They are shown with lsusb. Tested with the usual Kali compatible adapters, such as:
- MT7601 (two different form factors)
- RTL8187
- AR9271
I installed install firmware-linux-nonfree, but still no change. Using a USB-OTG adapter with additional plug for the power source. 

Thanks, a lot :)

**Comment by Shubhamvis98** [comment]
Hi @d4rkw1n9, most of the drivers are disabled in kernel as well. And that's mobian issue.

**Comment by Shubhamvis98** [comment]
I tried making the kernel but my poco f1's display isn't working properly. (I bought it refurbished). But if you want I'll send a kernel image to try. Then I'll publish the image in my repository.

**Comment by d4rkw1n9** [comment]
> I tried making the kernel but my poco f1's display isn't working properly. (I bought it refurbished). But if you want I'll send a kernel image to try. Then I'll publish the image in my repository if it worked as expected. 

Yea sure, you can send me the boot.img and I will test it. Just note that I have tianma (as opposed to the display of your device, I assume). 

I guess the OnePlus 6/T boot images does not contain the drivers either?

**Comment by Shubhamvis98** [comment]
I'll send you the DEB package tomorrow. You just need to install it on the OS and reboot.

**Comment by d4rkw1n9** [comment]
Cool, thanks in advance.

Aug 28, 2024 10:02:24 PM Shubham Vishwakarma ***@***.***>:

**Comment by Shubhamvis98** [comment]
Hi @d4rkw1n9,
Here's the [package](https://drive.google.com/file/d/1agtgOQfpzkdzP-Frq3u5yMlfwPbfuI3x/view?usp=sharing).
Could you please try this kernel and let me know if it works.
I've enabled below drivers:
- MT7601
- RTL8187
- AR9271

Please take Linux boot.img backup before installing this package, just in case you also face the same display issue.

**Comment by d4rkw1n9** [comment]
> Hi @d4rkw1n9, Here's the [package](https://file.io/a1kZybZ4z8bi). Could you please try this kernel and let me know if it works. I've enabled below drivers:
> 
> * MT7601
> * RTL8187
> * AR9271
> 
> Please take Linux boot.img backup before installing this package, just in case you also face the same display issue.

Hey there. Thanks for the package, I installed it right away. The device boots, but no touch inputs possible. I can ssh into my instance though.

This the install procedure:
`┌──(root㉿fossfrog)-[/home/kali/tmp]
└─# dpkg -i linux-image-6.9.0-sdm845_6.9.0-2_arm64.deb
Selecting previously unselected package linux-image-6.9.0-sdm845.
(Reading database ... 117229 files and directories currently installed.)
Preparing to unpack linux-image-6.9.0-sdm845_6.9.0-2_arm64.deb ...
Unpacking linux-image-6.9.0-sdm845 (6.9.0-2) ...
Setting up linux-image-6.9.0-sdm845 (6.9.0-2) ...
update-initramfs: Generating /boot/initrd.img-6.9.0-sdm845
W: Possible missing firmware /lib/firmware/qcom/a640_gmu.bin for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a630_zap.mbn for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a619_gmu.bin for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a615_zap.mbn for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a540_gpmu.fw2 for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a530_zap.b02 for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a530_zap.b01 for built-in driver msm
W: Possible missing firmware /lib/firmware/qcom/a530_zap.b00 for built-in driver msm
64+0 records in
64+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.337026 s, 199 MB/s
writing boot image config in bootimg.cfg
extracting kernel in zImage
extracting ramdisk in initrd.img
reading config file bootimg.cfg
reading kernel from kernel-6.9.0-sdm845
reading ramdisk from /boot/initrd.img-6.9.0-sdm845
Writing Boot Image boot.img
64+0 records in
64+0 records out
67108864 bytes (67 MB, 64 MiB) copied, 0.574979 s, 117 MB/s
/`

`lsusb` btw shows nothing again.

Best regards

**Comment by Shubhamvis98** [comment]
@d4rkw1n9 
are you using external power supplied usb hub?
also can you check modules in `lsmod`

**Comment by Shubhamvis98** [comment]
for touch inputs, try to run droid-juicer once and reboot
also don't forget to modify the dtb

**Comment by d4rkw1n9** [comment]
> for touch inputs, try to run droid-juicer once and reboot
> also don't forget to modify the dtb

I did modify the dtb, then flashed the resulting img, then installed your deb package. So then I need to redo the dtb mod again after installing the dep package?

**Comment by Shubhamvis98** [comment]
@d4rkw1n9 
I tried it myself and its working.

```
[  306.992214] usbcore: deregistering interface driver mt7601u
[  316.126762] usb 1-1.3: reset high-speed USB device number 4 using xhci-hcd
[  316.332027] mt7601u 1-1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[  316.336062] mt7601u 1-1.3:1.0: Firmware Version: 0.1.00 Build: 7640 Build time: 201302052146____
[  316.806742] mt7601u 1-1.3:1.0: EEPROM ver:0d fae:00
[  317.143993] ieee80211 phy2: Selected rate control algorithm 'minstrel_ht'
[  317.145721] usbcore: registered new interface driver mt7601u
                                                                                                                                                                                                                                           
┌──(root㉿fossfrog)-[/home/jack]
└─# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 80  bytes 7350 (7.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 80  bytes 7350 (7.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.50.53  netmask 255.255.255.0  broadcast 192.168.50.255
        inet6 fe80::58dc:fca2:bb17:c49c  prefixlen 64  scopeid 0x20<link>
        ether XX:XX:XX:XX:XX:XX  txqueuelen 1000  (Ethernet)
        RX packets 12896  bytes 14446357 (13.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7422  bytes 939518 (917.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether XX:XX:XX:XX:XX:XX  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

                                                                                                                                                                                                                                           
┌──(root㉿fossfrog)-[/home/jack]
└─# airmon-ng                

PHY     Interface       Driver          Chipset

phy0    wlan0           ath10k_snoc     Not pci, usb, or sdio
phy2    wlan1           mt7601u         Ralink Technology, Corp. MT7601U

```

**Comment by Shubhamvis98** [comment]
> > for touch inputs, try to run droid-juicer once and reboot
> > also don't forget to modify the dtb
> 
> I did modify the dtb, then flashed the resulting img, then installed your deb package. So then I need to redo the dtb mod again after installing the dep package?

You have to modify dtb at the end. I mean after installing kernel package or running droid-juicer. Whenever initramfs gets updated then boot.img gets flashed with default dtb.

**Comment by d4rkw1n9** [comment]
> > > for touch inputs, try to run droid-juicer once and reboot
> > > also don't forget to modify the dtb
> > 
> > I did modify the dtb, then flashed the resulting img, then installed your deb package. So then I need to redo the dtb mod again after installing the dep package?
> 
> You have to modify dtb at the end. I mean after installing kernel package or running droid-juicer. Whenever initramfs gets updated then boot.img gets flashed with default dtb.

Ok, got it:

1) deb package -> reboot
2) droid-juicer
3) dtb mod
4) flash resulting boot img

Will test it now and let you know. Thanks anyways for your great work and support!

**Comment by Shubhamvis98** [comment]
@d4rkw1n9 
touch is not working in my build as well. seems i did something wrong while building the kernel

**Comment by d4rkw1n9** [comment]
> @d4rkw1n9 
> touch is not working in my build as well. seems i did something wrong while building the kernel

Ah okay, in that case I'll wait with reinstalling it 👍

**Comment by Shubhamvis98** [comment]
i'm rebuilding it again. i'll send you a new package after testing.

**Comment by Shubhamvis98** [comment]
@d4rkw1n9
Try this [image](https://file.io/7TnBo4E2hDKr)
Touch is working as well.

Remove the previous package before installing this one otherwise the boot flasher script won't work.
then install this package
modify dtb
and reboot

**Comment by d4rkw1n9** [comment]
> @d4rkw1n9 Try this [image](https://file.io/7TnBo4E2hDKr) Touch is working as well.
> 
> Remove the previous package before installing this one otherwise the boot flasher script won't work. then install this package modify dtb and reboot

Thx. Repeated the steps I outlined above (with uninstalling old deb package first, and installing new one, then modifying dtb and flashing new boot.img), but without success. lsmod does not show the mt7601, hence also not shown as wlan1. also modprobe -> no result. 

Would it be possible, if you find time ofc, to send me the working boot.img with dtb modification and deb package / drivers included, for tianma display pls? Or do you have any other idea or steps I have to take? 

Thanks, once more :)

**Comment by Shubhamvis98** [comment]
can you send me your dts file that you modified.

**Comment by Shubhamvis98** [comment]
and what about dmesg log. do you see the adapter logs?

**Comment by Shubhamvis98** [comment]
@d4rkw1n9
here's the [zImage](https://file.io/wbtUmgy27OuJ)
replace this in your boot.img and try to boot.

download the file
put boot.img and downloaded zImage file in same directory
and run `abootimg -u boot.img -k zImage`
then flash the boot.img

**Comment by d4rkw1n9** [comment]
> @d4rkw1n9
> here's the [zImage](https://file.io/wbtUmgy27OuJ)
> replace this in your boot.img and try to boot.
> 
> download the file
> put boot.img and downloaded zImage file in same directory
> and run `abootimg -u boot.img -k zImage`
> then flash the boot.img

Thanks for your support. Found the mistake on my side, I modified the wrong dtb file blindly following your other guide (6.6 instead of 6.6.44). Now it seems to work !! I love the possibility of dual booting.

Does the image for OnePlus 6T contain the drivers already? I am thinking about getting a cheap but broken 6T, repair it and install dual boot there as well. As it has AB partitioning, OS is supposed to be switchable without always flashing different boot.img from orangefox.

**Comment by Shubhamvis98** [comment]
it seems you've missed my ramdisk-merger project (-;

**Comment by Shubhamvis98** [comment]
watch [this](https://youtube.com/shorts/CvUtKTKKLbo?feature=share)

**Comment by Shubhamvis98** [comment]
i'll publish the new kernel image on my apt repository. then the drivers will work on all sdm845 devices.

**Comment by d4rkw1n9** [comment]
> i'll publish the new kernel image on my apt repository. then the drivers will work on all sdm845 devices.

Nice! I guess I will need to change to 6T anyways, as updating the kali kernel on the POCO F1 means dtb mod again :D

**Comment by Shubhamvis98** [comment]
> > i'll publish the new kernel image on my apt repository. then the drivers will work on all sdm845 devices.
> 
> Nice! I guess I will need to change to 6T anyways, as updating the kali kernel on the POCO F1 means dtb mod again :D

That's one, and the second is an external power source for the USB hub. Other than that, it's a great phone. I also bought it refurbished for half the price of a refurbished OnePlus 6.
