### ISSUE TITLE
[Question] Waydroid Support?

### ISSUE THREAD

**Issue by d4rkw1n9** [Shubhamvis98/kali-pinephone#45]
Hey there

Just wanted to ask whether there is a way to get Waydroid up and running on this image?

Thx

**Comment by Shubhamvis98** [comment]
Hey @d4rkw1n9,
Waydroid is running properly in kali nethunter pro.

**Comment by d4rkw1n9** [comment]
> Hey @d4rkw1n9,
> Waydroid is running properly in kali nethunter pro.
> Please read the installation wiki of waydroid.

Just saw your video on youtube where you showed how to install on nethunter pro. Worked, thanks. 

Only thing is the resolution of waydroid is only half the screen of the phone. Will investigate, I close this question.

**Comment by Shubhamvis98** [comment]
> > Hey @d4rkw1n9,
> > Waydroid is running properly in kali nethunter pro.
> > Please read the installation wiki of waydroid.
> 
> Just saw your video on youtube where you showed how to install on nethunter pro. Worked, thanks.
> 
> Only thing is the resolution of waydroid is only half the screen of the phone. Will investigate, I close this question.

That's why mentioned that reboot after running `waydroid init`
then open waydroid.
