### ISSUE TITLE
Pocof1 cannot use OTG devices. Also unable to use wlan0mon

### ISSUE THREAD

**Issue by BG7UHS** [Shubhamvis98/kali-pinephone#46]
Pocof1 cannot use OTG devices. Also unable to use wlan0mon

**Comment by Shubhamvis98** [comment]
Hi @BG7UHS,
for OTG, please refer to this issue #43
Also for internal mon mode, it's still under development for mainline kernel.

**Comment by BG7UHS** [comment]
I looked at other issues that were closed. Already got the gist of it.

**Comment by BG7UHS** [comment]
> Hi @BG7UHS, for OTG, please refer to this issue #43 Also for internal mon mode, it's still under development for mainline kernel.

Thank you so much for your effort.
