### ISSUE TITLE
[fajita] USB - OTG

### ISSUE THREAD

**Issue by yurnam** [Shubhamvis98/kali-pinephone#48]
Hi! Are there any available resources or information on how to get OTG working on the OnePlus 6T?

**Comment by Shubhamvis98** [comment]
Hi @yurnam,
It should be working on op6/6t.

Can you check dmesg logs?
And what usb device you're trying?

**Comment by yurnam** [comment]
I have tried multiple devices, like USB flash drives and USB-C to Ethernet adapters, but none of them worked. The dmesg log shows no related messages to usb when connecting or disconnecting a USB device,  lsusb output is empty. 
on android everything works fine.

**Comment by Shubhamvis98** [comment]
@yurnam that's due to the kernel. Most of the features are disabled in the kernel. So to make otg work we need to recompile the kernel with necessary features.

**Comment by Shubhamvis98** [comment]
I've just added nh kernel in my repository for sdm845 devices. Users who are facing issues with wifi adapters can try to install the sdm845-nh-support package.

**Comment by aantelo** [comment]
> I've just added nh kernel in my repository for sdm845 devices. Users who are facing issues with wifi adapters can try to install the sdm845-nh-support package.

how can do this?

**Comment by Shubhamvis98** [comment]
Nethunter kernel is already installed in the recent release.

**Comment by aantelo** [comment]
> Nethunter kernel is already installed in the recent release.
Thanks for your time:

the only version that boots is the one provided in the official kali page but doees not work wifi and usb . I tried with kali_phosh_sdm845_20241104 it does not boot.. it get stuck and shows (initramfs) messages.
I'm testing on Xiaomi Mix 2s.(Polaris) btw
