### ISSUE TITLE
connector adapter not working properly

### ISSUE THREAD

**Issue by safarifox** [Shubhamvis98/kali-pinephone#5]
connector adapter works only for charging, when inserted alfa adapter to it , it was not detected..
please fix

**Comment by Shubhamvis98** [comment]
can you check dmesg log and provide the output here after plugging in alfa adapter

**Comment by safarifox** [comment]
please find
its like 3800 lines of this 

```
[ 3705.470951] sun8i-dw-hdmi 1ee0000.hdmi: EVENT=plugout
[ 3706.495169] sun8i-dw-hdmi 1ee0000.hdmi: EVENT=plugout
[ 3707.522159] sun8i-dw-hdmi 1ee0000.hdmi: EVENT=plugout
[ 3708.542944] sun8i-dw-hdmi 1ee0000.hdmi: EVENT=plugout
```

but strange its sound like it can see adapter .. 


![kali7771](https://user-images.githubusercontent.com/104325393/178146517-acf09779-4fb5-4e69-90fc-926f63a5ca97.jpg)

**Comment by safarifox** [comment]
answer awus036ac (that is supported by kali) is not supported (maybe coz its a hight power one)
