### ISSUE TITLE
Oneplus 6T Not Booting !

### ISSUE THREAD

**Issue by DiveshDR** [Shubhamvis98/kali-pinephone#50]
Today I Flashed On Oneplus 6T And!
[image](https://github.com/user-attachments/assets/14b54223-fbb1-4337-afcb-3eadd35e7fb4) 
[image](https://github.com/user-attachments/assets/be06aab6-20d2-4f13-8a28-d72859d20563)

 After Reboot, It's Not Booting. It is booting into fastboot mode!
 [Fastboot Image](https://github.com/user-attachments/assets/757154d6-44cf-475a-a51f-a88c4bd85080) 
Sorry for the bad photo quality. I used a Laptop webcam thank you, I hope it will fix soon. I'm excited to try it!

**Comment by Shubhamvis98** [comment]
Hi @DiveshDR,
The image is working fine in Op6/6t.
Could you try to flash the boot.img again and boot it.

**Comment by DiveshDR** [comment]
Hiii @Shubhamvis98 

bro you forgot to mention to erase dtbo

" fastboot erase dtbo"

please mention that in installation prosses.

thank you ; )

**Comment by Shubhamvis98** [comment]
Hey @DiveshDR,
Yeah, I totally forgot about dtbo (-;
I'll update the commands in release in few minutes.
Thanks

**Comment by Shubhamvis98** [comment]
Hi @DiveshDR,
Is touchscreen working in op6?

**Comment by DiveshDR** [comment]
@Shubhamvis98 Yes Its Working, But after Some Idle Time its getting stuck, then forced reboot required.
and phone call audio not audible

**Comment by Shubhamvis98** [comment]
Have you tried playing music files or online vids? Is audio working there?
