### ISSUE TITLE
Touch not working on OnePlus 6T(Fajita)

### ISSUE THREAD

**Issue by parth-android** [Shubhamvis98/kali-pinephone#51]
After booting up for the first time, the touchscreen on my device is not functioning. Additionally, OTG is not working either. I've tried connecting an OTG mouse and keyboard, but they are also unresponsive.

**Comment by parth-android** [comment]
Edit :- Apparently, I was using an image file from the official website with a build date of 2308. When I checked the release section on GitHub, I saw that the latest build was 1308. Now that I've downgraded to the 1308 build, the touchscreen is working properly.

**Comment by Shubhamvis98** [comment]
Hi @parth-android, It's not downgraded btw. I make my own releases without kali themes and i add my custom tweaks in github releases. so both releases are almost same. there's not much difference.

**Comment by parth-android** [comment]
Ahhh... That means the official Nethunter build have some issues related to touch panels also it freezes after installation even volume/power button is not working.

**Comment by Shubhamvis98** [comment]
I didn't say that the touch isn't working in official release.

**Comment by parth-android** [comment]
I just flashed official build again and it freezes nothing is working. But the GitHub one is working fine.

**Comment by Shubhamvis98** [comment]
I tried the official one in my pocof1 and it was working. Not sure what's the issue with op6. But I know that there's not much difference at the kernel level in both builds.

**Comment by parth-android** [comment]
Is there anything that triggers original touchpanel driver like project renegade (Windows 10/11) do?
As I have replaced my Screen(third-party screen from local market) 6 months ago and after that my touch stopped working on windows ARM.

**Comment by Shubhamvis98** [comment]
Not sure.
