### ISSUE TITLE
Keyboard Arrow

### ISSUE THREAD

**Issue by Kalisabbb** [Shubhamvis98/kali-pinephone#55]
Hello congrats for the work!!!

But I have a problem with the keyboard arrows. .I can't see in a oneplus6 with nh pro...
![IMG_20240919_114236.jpg](https://github.com/user-attachments/assets/bb552d0c-314e-4348-a8eb-7c29515794a4)

**Comment by Kalisabbb** [comment]
Gesture... 😍 Amazing

**Comment by Shubhamvis98** [comment]
It's a new keyboard app. Use space r for arrow key functions. Hold space a d drag.
