### ISSUE TITLE
internal bios memeory is not supported

### ISSUE THREAD

**Issue by safarifox** [Shubhamvis98/kali-pinephone#6]
internal bios memory is dead for some reason
every time have to set time manually ..
sudo date -s "10 JUL 2022 10:00:00" (if someone need a command)

sudo timedatectl set-ntp on gives error is well :
Failes to set ntp: NTP not supported

**Comment by Shubhamvis98** [comment]
install systemd-timesyncd package using apt, this will fix the time and data update issue.
after installing this package, you'll see time & date auto-update switch on settings
