### ISSUE TITLE
oneplus6t[fajita] usb wifi kernel

### ISSUE THREAD

**Issue by 17U** [Shubhamvis98/kali-pinephone#60]
I would like to ask the author which kernel source code you are using. Could you also send me the link? Looking forward to your reply. Thank you

**Comment by Shubhamvis98** [comment]
Check for mobian repository.

**Comment by 17U** [comment]
> 您可以在官方 mobian 存储库中找到内核源代码。我们还没有为 nhpro 定制内核。

I tried compiling sdm845-linux-mobian-6.6 from the official MOBIAN repository, but after flashing it, I couldn't boot up. Could you please teach me the link to the kernel source code you are using, the configuration file, and the compilation steps? Looking forward to your reply

> You can find the kernel source in official mobian repository. We don't have any custom kernel for nhpro yet.

I tried compiling sdm845-linux-mobian-6.6 from the official MOBIAN repository, but after flashing it, I couldn't boot up. Could you please teach me the link to the kernel source code you are using, the configuration file, and the compilation steps? Looking forward to your reply

**Comment by Shubhamvis98** [comment]
I'm not using any custom kernel. I installed the kernel from mobian repository, same as yours. Also the kernel source is the same you've compiled.

**Comment by 17U** [comment]
> I'm not using any custom kernel. I installed the kernel from mobian repository, same as yours. Also the kernel source is the same you've compiled.

think you very much,Can you send the link to the mobian kernel repository? Looking forward to your reply

**Comment by Shubhamvis98** [comment]
Hi @17U,
Here's the kernel repository link: https://salsa.debian.org/Mobian-team/devices/kernels/sdm845-linux

**Comment by 17U** [comment]
> Hi @17U, Here's the kernel repository link: https://salsa.debian.org/Mobian-team/devices/kernels/sdm845-linux

think your very much!

**Comment by Shubhamvis98** [comment]
I've just added nh kernel in my repository for sdm845 devices. Users who are facing issues with wifi adapters can try to install the sdm845-nh-support package.
