### ISSUE TITLE
Bluetooth problem Pocof1

### ISSUE THREAD

**Issue by Kalisabbb** [Shubhamvis98/kali-pinephone#61]
I cant enable Bluetooth switch...
And in the terminal too

![IMG_20240930_190148.jpg](https://github.com/user-attachments/assets/38a886ed-4b01-4bed-810a-0fe756899bea)

![IMG_20240929_231551.jpg](https://github.com/user-attachments/assets/083637b4-5dae-4049-b287-43a0408e7efe)

But I can make

Sudo hciconfig hci0 up

Thanks

**Comment by Shubhamvis98** [comment]
Enable Bluetooth service. It's working fine.
