### ISSUE TITLE
POCO F1 (boot_beryllium-tianma_20240813.img) NO CELLULAR, NO WI-FI 

### ISSUE THREAD

**Issue by deshi-8** [Shubhamvis98/kali-pinephone#64]
Hi there, I'm not able to activate any wireless connection, just Bluetooth. As you can see the settings menu ¨WIFI¨ is gone. Thanks
![IMG_7313](https://github.com/user-attachments/assets/5f2424c9-7d77-4215-98f5-30e605e1bd22)
![IMG_7312](https://github.com/user-attachments/assets/273c71bf-6755-4923-abd9-4dee8201259b)
![IMG_7311](https://github.com/user-attachments/assets/48b2e32e-ea29-4c33-889e-4838c82abbde)

**Comment by deshi-8** [comment]
I forgot to mention, I used the SD card method.

**Comment by Shubhamvis98** [comment]
Hi @deshi-8, can you check the kernel logs as well. see if all firmwares are loaded. you can run `dmesg | grep mbn`

**Comment by deshi-8** [comment]
I just flashed your new release and it looks great. Nice keyboard, and Nethunter App. Still can't use bluetooth... any advice? Thanks.

**Comment by Shubhamvis98** [comment]
Can you provide logs/hciconfig output.
