### ISSUE TITLE
Focaltech FTS Touchscreen

### ISSUE THREAD

**Issue by WaldoPepper** [Shubhamvis98/kali-pinephone#66]
Hi,

my Pocophone F1 ssems to have a Focaltech FTS touchscreen (if I interpret this correctly):

![image](https://github.com/user-attachments/assets/0060a246-1d1a-408c-8746-a7a24558ea57)

Will any of the ebbg or tianma releases work on this phone?

**Comment by Shubhamvis98** [comment]
Check the output of `cat /proc/cmdline`
Read below wiki:
https://wiki.postmarketos.org/wiki/Xiaomi_POCO_F1_(xiaomi-beryllium)

**Comment by WaldoPepper** [comment]
![image](https://github.com/user-attachments/assets/3e708ff1-9eaf-4533-b240-c298ef839163)

...seems I have to root first....

**Comment by WaldoPepper** [comment]
Ok, unlocked BL, rooted and got:
```
msm_drm.dsi_display0=dsi_ebbg_fhd_ft8719_video_display
```

So I will need ebbg, many thanks for helping me out!

**Comment by Shubhamvis98** [comment]
Is it ok to close this issue?
