### ISSUE TITLE
OnePlus 6T{Fajita} Flash Warning

### ISSUE THREAD

**Issue by w0lt41r** [Shubhamvis98/kali-pinephone#78]
Hey awesome dev, I just tried to flash the latest SDM845 20241104 release on my oneplus 6T and upon flashing userdata image it gave the following warning:
`└─$ fastboot flash userdata kali_phosh_sdm845_20241104.img
Warning: skip copying userdata image avb footer (userdata partition size: 118112366592, userdata image size: 140239813529576).`

On checking the image size i get the following:
`──(kali㉿kali)-[~/Nethunter-Pro/patched_ones]
└─$ ls -lh kali_phosh_sdm845_20241104.img 
-rwxrw-rw- 1 kali kali 3.0G Dec  9 16:39 kali_phosh_sdm845_20241104.img`

The above shows correct image size but why fastboot misinterprets it?
However the image is successfully flashed and its working. Thanks for your time.

**Comment by Shubhamvis98** [comment]
The image is a sparse image file, which is a fastboot flash-friendly filesystem. When we convert a raw image to a sparse image, it reduces the file size as well. When we flash it using fastboot, the file is decompressed at flash time.

**Comment by w0lt41r** [comment]
So we can just ignore the warning? by the way thanks!

**Comment by Shubhamvis98** [comment]
Yes, you can ignore that warning.
