### ISSUE TITLE
PinePhone/Pro Release 20241221 Only for PinePhone?

### ISSUE THREAD

**Issue by deshi-8** [Shubhamvis98/kali-pinephone#86]
It would work on the other SDM845 devices?

**Comment by Shubhamvis98** [comment]
If the name is PinePhone/Pro, then why would it work on SDM845? I use the SDM845 tag for SDM845 images. You should check the other tags.

**Comment by deshi-8** [comment]
Are you sure?

**Comment by Shubhamvis98** [comment]
Give it a try then.

**Comment by Shubhamvis98** [comment]
Although you can boot the rootfs but you need the device-specific kernel/boot.img

**Comment by Shubhamvis98** [comment]
> Just kidding buddy, great work by the way. Waiting for a new release for the other devices. Peace.

(-;

**Comment by deshi-8** [comment]
It sounds interesting, but I don't want mess with the set up that I got already. I'm not in a hurry, I'll wait for your next stable release, but thanks anyways.

**Comment by Shubhamvis98** [comment]
I recently released SDM845 image, last month I guess.
